layout_spectrum: 1
typography_spectrum: 0.8190118
color:
  saturation: 0.4838883
  lightness: 0.1305048
  brandStrength: 0
  rhythmicContrast: 0.7653061
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
name: Discotto
